console.log;
console.log.bind;
console.warn;
console.warn.bind;
console.error;
console.error.bind;
console.group;
console.group.bind;
console.groupEnd;
console.groupEnd.bind;
var encodeURIComponent;
var decodeURIComponent;
Window.prototype.document;
Window.prototype.requestAnimationFrame;
Window.prototype.webkitRequestAnimationFrame;
Window.prototype.mozRequestAnimationFrame;
Window.prototype.msRequestAnimationFrame;
Window.prototype.URL;
Window.prototype.URL.revokeObjectURL;
Object.end;
Object.join;
Object.select;
Object.sep;
Object.request;
Object.get;
Object.Fragment;
Object.index;
Object.exec;
Object.getContext;
Object.value;
Object.findDOMNode;
Object.Component;
Object.Component.call;
Object.width;
Object.onclick;
Object.Children;
Object.Children.toArray;
Object.font;
Object.write;
Object.style;
Object.style.position;
Object.style.left;
Object.click;
Object.document;
Object.document.getElementById;
Object.document.open;
Object.document.write;
Object.document.close;
Object.innerHTML;
Object.measureText;
Object.render;
Object.setAttribute;
Object.out;
Object.out.println;
Object.id;
Object.resolve;
Object.createElement;
Object.createElement.apply;
Object.appendChild;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Object.on;
var clearInterval;
HTMLDocument.prototype.getElementById;
HTMLDocument.prototype.getElementsByTagName;
HTMLDocument.prototype.activeElement;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.querySelector;
HTMLDocument.prototype.execCommand;
var cljs;
cljs.user;
var SyntaxError;
var ReactDOM;
ReactDOM.findDOMNode;
ReactDOM.unmountComponentAtNode;
ReactDOM.render;
var URIError;
var Buffer;
Buffer.byteLength;
TypeError.prototype.toString;
var RESULT;
RESULT.prototype.catch$;
goog.dependencies_;
goog.dependencies_.nameToPath;
goog.dependencies_.written;
goog.dependencies_.visited;
goog.basePath;
goog.global;
goog.global.document;
goog.require_figwheel_backup_;
goog.require;
goog.DEBUG;
goog.require__;
goog.string;
goog.string.StringBuffer;
goog.string.StringBuffer.prototype.append;
goog.string.StringBuffer.prototype.getLength;
goog.isProvided_;
goog.cljsReloadAll_;
var marked;
var process;
process.hrtime;
JSON.parse;
var require;
require.cache;
require.resolve;
var setInterval;
var RangeError;
var setTimeout;
var createReactClass;
var figwheel;
figwheel.repl;
figwheel.repl.after_reloads;
figwheel.core;
figwheel.core.logger;
var FlipMove;
document.createElement;
document.title;
document.createTextNode;
document.body;
document.getElementById;
var Highlight;
HTMLBodyElement.prototype.addEventListener;
HTMLBodyElement.prototype.appendChild;
HTMLBodyElement.prototype.removeChild;
var React;
React.createElement;
React.Component;
React.Component.call;
React.initializeTouchEvents;
RegExp.prototype.bidi$bidi$PatternSegment$;
RegExp.prototype.bidi$bidi$PatternSegment$segment_regex_group$arity$1;
RegExp.prototype.pattern;
RegExp.prototype.bidi$bidi$Pattern$match_pattern$arity$2;
RegExp.prototype.bidi$bidi$PatternSegment$matches_QMARK_$arity$2;
RegExp.prototype.bidi$bidi$Pattern$unmatch_pattern$arity$2;
RegExp.prototype.bidi$bidi$PatternSegment$param_key$arity$1;
RegExp.prototype.bidi$bidi$PatternSegment$transform_param$arity$1;
RegExp.prototype.bidi$bidi$Pattern$;
var Java;
Java.type;
var EvalError;
var ReactDOMServer;
ReactDOMServer.renderToString;
