console.log;
console.log.bind;
console.warn;
console.warn.bind;
console.error;
console.error.bind;
console.group;
console.group.bind;
console.groupEnd;
console.groupEnd.bind;
Window.prototype.document;
Window.prototype.requestAnimationFrame;
Window.prototype.webkitRequestAnimationFrame;
Window.prototype.mozRequestAnimationFrame;
Window.prototype.msRequestAnimationFrame;
Window.prototype.URL;
Window.prototype.URL.revokeObjectURL;
Object.initStorageEvent;
Object.defaultValue;
Object.onChange;
Object.Fragment;
Object.index;
Object.exec;
Object.value;
Object.findDOMNode;
Object.Component;
Object.Component.call;
Object.Children;
Object.Children.toArray;
Object.click;
Object.render;
Object.setAttribute;
Object.out;
Object.out.println;
Object.createElement;
Object.createElement.apply;
Object.unmountComponentAtNode;
Object.error;
Object.error.println;
Object.hasOwnProperty;
Navigator.prototype.canShare;
HTMLDocument.prototype.createEvent;
HTMLDocument.prototype.activeElement;
HTMLDocument.prototype.createElement;
HTMLDocument.prototype.getElementById;
var SyntaxError;
var confirm;
var URIError;
var RESULT;
RESULT.prototype.catch$;
var process;
process.hrtime;
var require;
require.resolve;
var RangeError;
var setTimeout;
var JSJodaLocale;
HTMLBodyElement.prototype.appendChild;
HTMLBodyElement.prototype.removeChild;
var React;
React.Component;
React.Component.prototype.forceUpdate;
React.Component.prototype.cljsIsDirty;
React.Component.prototype.constructor$;
React.Component.prototype.props;
React.Component.prototype.props.argv;
React.Component.prototype.props.children;
Date.prototype.tick$core$ITimeShift$forward_duration$arity$2;
Date.prototype.tick$core$IConversion$zoned_date_time$arity$1;
Date.prototype.tick$core$ITimeShift$backward_duration$arity$2;
Date.prototype.tick$core$ITimeSpan$;
Date.prototype.tick$core$ITimeReify$in$arity$2;
Date.prototype.tick$core$ITimeComparison$_GT_$arity$2;
Date.prototype.tick$core$IExtraction$;
Date.prototype.tick$core$IBetween$;
Date.prototype.tick$core$IConversion$offset_date_time$arity$1;
Date.prototype.tick$core$ITimeReify$;
Date.prototype.tick$core$IExtraction$date_time$arity$1;
Date.prototype.tick$core$ITimeComparison$;
Date.prototype.tick$core$IConversion$instant$arity$1;
Date.prototype.tick$core$ILocalTime$local_QMARK_$arity$1;
Date.prototype.tick$core$IExtraction$year$arity$1;
Date.prototype.tick$core$ITimeComparison$_GT__EQ_$arity$2;
Date.prototype.tick$core$ITimeComparison$_LT__EQ_$arity$2;
Date.prototype.tick$core$ITimeShift$;
Date.prototype.tick$core$ITimeSpan$beginning$arity$1;
Date.prototype.tick$core$IExtraction$date$arity$1;
Date.prototype.tick$interval$ITimeSpanable$temporal_value$arity$1;
Date.prototype.tick$core$IConversion$inst$arity$1;
Date.prototype.tick$core$IBetween$between$arity$2;
Date.prototype.tick$core$ILocalTime$;
Date.prototype.tick$core$IExtraction$year_month$arity$1;
Date.prototype.tick$core$IConversion$;
Date.prototype.tick$interval$ITimeSpanable$;
Date.prototype.tick$core$ITimeSpan$end$arity$1;
Date.prototype.tick$core$ITimeComparison$_LT_$arity$2;
var Java;
Java.type;
var EvalError;
